; Auto-generated by Agentic — Developer panel
[Setup]
AppId={{A6E2B7D3-1F4E-4B2A-8C5D-AGENTICAPP00001}}
AppName=Agentic
AppVersion=1.0.0
AppPublisher=Agentic
DefaultDirName={localappdata}\Programs\Agentic
DefaultGroupName=Agentic
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\Gentian\AsPro\AI\Agentic\installer\Output
OutputBaseFilename=AgenticSetup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayIcon={app}\agentic.exe

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Users\Gentian\AsPro\AI\Agentic\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Gentian\AsPro\AI\Agentic\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\Agentic"; Filename: "{app}\agentic.exe"
Name: "{userdesktop}\Agentic"; Filename: "{app}\agentic.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Run]
Filename: "{app}\agentic.exe"; Description: "Launch Agentic"; Flags: nowait postinstall skipifsilent
